### ISSUE TITLE
Arm away time configuration/instant arm away

### ISSUE THREAD

**Issue by smwoodward** [roopesh/ad-qolsys#8]
It wouldn’t be a bad idea to have the arm away setting to be configurable. My setup is that if the panel is armed away with the delay, and a door isn’t opened during the count down, it will automatically switch to armed stay.  This presents a problem where we normally arm the house with home kit or home assistant when we are outside of the house in the car.

**Comment by roopesh** [comment]
Is that setup defined in the panel or in HA?

**Comment by smwoodward** [comment]
> Is that setup defined in the panel or in HA?

That is defined in the panel.

**Comment by roopesh** [comment]
Then I don't understand this request.  What would the enhancement be here?

**Comment by smwoodward** [comment]
Ok, so my alarm panel is setup where if you hit the arm away button it starts the countdown to allow you to exit, if the door is not opened during the countdown, then the panel automatically changes to arm stay.  This is a configuration in the panel. 

The arm away command that is currently being sent from AD defaults to the 60 second exit delay.  If you arm away the panel from home assistant while you are outside of your house, then a door will never be opened and at the end of the 60 second exit delay, it will change to arm stay. I ran into this issue after I reversed engineered the arming commands and was running it in node red. 

The solution I found here https://community.home-assistant.io/t/qolsys-iq-panel-2-and-3rd-party-integration/231405/115?u=smwoodward is that adding "delay: 0" to the json arm away command fixed this issue and the panel would arm away and not automatically change over to arm stay. 

It wouldn't be a bad idea to add a configuration variable for the default delay time and have the arm away command add the delay: XX to the command, and default the variable to 60, but allow it to be changed for cases like mine.

**Comment by roopesh** [comment]
Is that kinda like an "Arm Away (Instant)"?

**Comment by smwoodward** [comment]
It is instant arm away, but there isn't a command that can be sent over the ssl connection to the panel for arm away instant. 

I know I could change the setting in the panel, but I do have a need to keep the automatic swap from away to stay if a door isn't open and I also need to keep it to have an exit delay if armed from the panel but allow for remote arming away without changing over to arm stay. This is where I changed my node red flow to add delay:0 and it fixed that problem. Without delay:0 it defaults to a 60 second exit delay.

**Comment by roopesh** [comment]
Try the 1.7.0 beta release - let me know if that solves your problem.  You can test the new instant arm away with a button (here's mine) - be sure to put your token in:

```
type: button
tap_action:
  action: call-service
  service: mqtt.publish
  service_data:
    payload: >-
      {"instant": true, "event":"ARM","arm_type":"away","token":"<token>","partition_id":0}
    topic: qolsys/requests
  target: {}
entity: alarm_control_panel.doors_and_sliders
name: Arm Away (Instant)
show_icon: false
```
